### ISSUE TITLE
create release

### ISSUE THREAD

**Issue by TobiasKain** [TobiasKain/cnl2asp#35]

**Comment by TobiasKain** [comment]
javafx.fxml.LoadException: 
unknown path

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)
	at at.tuwien.gui.MainGuiController.createNewTab(MainGuiController.java:361)
	at at.tuwien.gui.MainGuiController.initialize(MainGuiController.java:71)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at at.tuwien.Main.start(Main.java:27)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418)
	at at.tuwien.gui.TranslationTabController.loadSentencePatterns(TranslationTabController.java:231)
	at at.tuwien.gui.TranslationTabController.initialize(TranslationTabController.java:119)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
